name: Verify regex in files

on:
  push:
#    branches:
#      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Install dependencies
#        run: npm install

      - name: Verify regex in files
        run: node tools/regex.js
